import { getCloudflareContext } from "@opennextjs/cloudflare";

// R2Bucket is a global type generated by `pnpm cf-typegen` (cloudflare-env.d.ts).

/**
 * Base prefix inside the bucket under which the image folders live.
 * Configurable per environment (BASE_PREFIX) in case you reorganize the bucket.
 * Normalized to guarantee exactly one trailing slash and no leading one.
 */
export const BASE_PREFIX: string = normalizePrefix(
  process.env.BASE_PREFIX ?? "Imagenes anteriores/",
);

function normalizePrefix(prefix: string): string {
  const trimmed = prefix.replace(/^\/+/, "").replace(/\/+$/, "");
  return trimmed.length ? `${trimmed}/` : "";
}

/**
 * Returns the R2 binding. The binding name (IMAGENES_BUCKET) is defined in
 * wrangler.jsonc; if you rename it, change it here in a single place.
 *
 * Uses the `async` mode of getCloudflareContext: it's the one that works in any
 * context (Server Components in `next dev`, remote bindings) and also in
 * production.
 */
export async function getBucket(): Promise<R2Bucket> {
  const { env } = await getCloudflareContext({ async: true });
  const bucket = env.IMAGENES_BUCKET;
  if (!bucket) {
    throw new Error(
      "El binding R2 'IMAGENES_BUCKET' no está disponible. Revisa wrangler.jsonc " +
        "y que estés ejecutando dentro del contexto de Cloudflare.",
    );
  }
  return bucket;
}
